### ISSUE TITLE
Messages not displayed on bundled app

### ISSUE THREAD

**Issue by tferreira** [GamingBud/DefChat#6]
Hi!

I encountered a wierd behaviour when using v0.555.

Posting a message to DefChat when running my project from Defold (Ctrl+B) works perfectly.
However, when I do a Windows Bundle and then run the executable, all messages posted to DefChat won't appear. 

Any ideas ? Might it be because of some system colors or fonts issues ?

Thanks again.

**Comment by GamingBud** [comment]
Hello!

That is strange... I ran my own test by bundling with the raw component. The only thing I added would be an alarm which posted a message every 2 seconds, as seen here:

![untitled](https://user-images.githubusercontent.com/11013079/39416230-018681c8-4c11-11e8-8fd2-4048137b0bf8.png)

It could very well be a font or node color issue, but that _should_ appear during a build test. The odd thing is that you encountered it _after_ bundling.

1. **Do you notice any msg.post or DefChat errors in the console while _building_?**
2. **Search for this line in the console: "DEF_CHAT:INSTANT_STAMPED", or, if you're not using Instant_Stamp, use "DEF_CHAT:STAMPED". If any messages were printed, they'd show up with this search.**
3. **If you found something on (2.) then check this:**

![untitled](https://user-images.githubusercontent.com/11013079/39416551-741bdf24-4c13-11e8-80a7-0e0ee2eb55cb.png)

**The color that is set here, unless otherwise edited by you, will be the color of the chat messages.**

**Comment by tferreira** [comment]
Hey, thank you for investigating.

So, no I don't have any errors in the console.
Here is the debug log on the bundled version (and it's exactly the same output as running it within Defold):

```
DEBUG:SCRIPT: DEF_CHAT:FONTS:ACQUIRED:
DEBUG:SCRIPT:
{
  Second_Example = {
    name = hash: [Second_Example],
  }
  default = {
    name = hash: [Example],
  }
}

DEBUG:SCRIPT: DEF_CHAT:FONT:DEFAULT: [Example]

DEBUG:SCRIPT: DEF_CHAT:HIDDEN_CHARACTERS:
DEBUG:SCRIPT: DEF_CHAT:LINEBREAKER:REACHED_END

DEBUG:SCRIPT: DEF_CHAT:LINEBREAKER:NO_LINEBREAKS
DEBUG:SCRIPT: DEF_CHAT:CHAT_BUILDER:POSITION_LINEBREAK_ADJUSTION: [-185.000000, -34.000000, 1.000000]
DEBUG:SCRIPT: DEF_CHAT:CHAT_BUILDER:ADJUSTION_DIFFERENCE: vmath.vector3(0, -8.5, 0)

DEBUG:SCRIPT: DEF_CHAT:CHAT:RECEIVED_TEXT: test
DEBUG:SCRIPT: DEF_CHAT:STRING:LENGTH: 0
DEBUG:SCRIPT: DEF_CHAT:INSTANT_STAMPED:
test
```

It happens also when typing messages. Not only posting messages to DefChat.
ChatText color is the same as yours.

I'm going to go more into this, and make sure it's not a side effect from my own code.

**Comment by tferreira** [comment]
Sorry for this, I've run a `git bisect` and found that it is a conflict with another GUI library.
I still need to find out why adding another GUI makes DefChat chatbox text invisible.

**Comment by tferreira** [comment]
I had to use `gui.set_render_order()` on all my gui scripts to make sure they are drawn with the right index. DefChat was under another GUI scene.
